version: 2.1

orbs:
  node: circleci/node@l.l

jobs:
  build:
    executor:
      name: node/default
      tag: "10.4"
    steps:
      - checkout
      - node/with-cache:
        steps:
          -run: npm install
      -run: npm run test
# version: 2.1
# # Use a package of configuration called an orb.
# orbs:
#   # Declare a dependency on the welcome-orb
#   welcome: circleci/welcome-orb@0.4.1
# # Orchestrate or schedule a set of jobs
# workflows:
#   # Name the workflow "welcome"
#   welcome:
#     # Run the welcome/run job in its own container
#     jobs:
#       - welcome/run